# Generated by Django 3.2.16 on 2022-11-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
